# Generated by Django 5.1.4 on 2026-07-01 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date et heure de la demande."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçue"),
                            ("in_progress", "En cours"),
                            ("completed", "Répondue"),
                        ],
                        default="received",
                        help_text="Statut de traitement du SAR.",
                        max_length=20,
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, help_text="Date et heure de réponse.", null=True
                    ),
                ),
                (
                    "export_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 du fichier ou contenu exporté.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur ayant formulé la demande.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de données (SAR)",
                "verbose_name_plural": "Demandes de données (SAR)",
                "ordering": ["-requested_at"],
            },
        ),
    ]
