# Generated by Django 5.1.4 on 2026-07-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('quizzes', '0002_question_selected_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Classe à laquelle ce quiz est rattaché (espace enseignant).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.classe'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Gabarit enseignant (relecture/édition) — jamais joué directement.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='source_quiz',
            field=models.ForeignKey(blank=True, help_text='Gabarit dont ce quiz est une copie (rempli pour les copies étudiantes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_copies', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='published', help_text='Brouillon (en relecture) ou publié (visible/joué par les étudiants).', max_length=10),
        ),
    ]
